trigger:
  branches:
    include:
      - main
  paths:
    include:
      - api-specs/*.yaml

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: POSTMAN_API_KEY

steps:
- script: |
    curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
  displayName: 'Install Postman CLI'

- task: CmdLine@2
  displayName: 'Lint OAS Documents'
  inputs:
    script: |
      echo 'Logging in to Postman CLI...'
      postman login --with-api-key $(POSTMAN_API_KEY)

      echo 'Finding and linting changed API specs...'
      # Get list of changed *.yaml files in /api-specs relative to the target branch
      changed_files=$(git diff --name-only HEAD~1 HEAD | grep '^api-specs/.*\.yaml$' || true)

      if [ -z "$changed_files" ]; then
        echo "No changed YAML files in /api-specs."
        exit 0
      fi

      for file in $changed_files; do
        echo "Linting $file..."
        postman api lint "$(Build.SourcesDirectory)/$file" --integration-id 180758
      done
